### ISSUE TITLE
 Maestro mcz communication problem

### ISSUE THREAD

**Issue by PeterKalel** [SebLz/ha-addons#10]
Hello

I just installed the addon but when I look in the logs this is what I get: Sending packet PING data None
Received packet PONG data None

And when I launch the MCZ MEASTRO application on my smartphone, I see the stove information coming back in the logs.

Sending packet PING data None
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None

Help PLease

**Comment by SebLz** [comment]
Hello @PeterKalel, I think this is related to the pipolaq script itself, let's continue on this thread:
https://github.com/pipolaq/maestro/issues/3
