### ISSUE TITLE
Suddlenly connection is impossible

### ISSUE THREAD

**Issue by o0larrylurex0o** [SebLz/ha-addons#37]
Hello since this afternoon, I don't know when, the intergration stopped working.

there was no change on my HA instance, and my MCZ app is OK

Is it possible that MCZ changed something on their side ?

logs attached

[nouveau 3.txt](https://github.com/SebLz/ha-addons/files/11335347/nouveau.3.txt)

Thx a lot for your help

**Comment by k3ruakk** [comment]
Same problem here, looks like MCZ backend stopped working or banned us...

**Comment by o0larrylurex0o** [comment]
Android app is working though ... so I hope it is possible to get it to work again :)

**Comment by Geert10** [comment]
Same problem here

**Comment by monimiX** [comment]
Issue for me too, any fix about it yet ?

**Comment by wallo66** [comment]
same problem :-(

**Comment by mrVoltrix** [comment]
Here also :(

**Comment by monimiX** [comment]
I'm using the cloud version (encapsuled version of pipolaq) the version of pipolaq work well on my computer.

**Comment by SebLz** [comment]
Hello guys, I've updated the python packages following the remarks here:
https://github.com/pipolaq/maestro/issues/5
It seems to work correctly on my setup, can you confirm it also does for you ?

**Comment by monimiX** [comment]
I confirm : fixed with version 2.5

**Comment by kiloloz71** [comment]
Thanks a lot
Works fine again !!! 😃

**Comment by mrVoltrix** [comment]
Here it works also ;)

**Comment by imcaro** [comment]
Merci ça fonctionne

**Comment by k3ruakk** [comment]
Thanks a lot for the quick update!

**Comment by wallo66** [comment]
Good job!!! THX
