### ISSUE TITLE
No MQTT re-subscription if connection lost for Cloud script

### ISSUE THREAD

**Issue by smillier** [SebLz/ha-addons#52]
When using the cloud script, if for some reason, the MQTT server connection is lost (server restart, network outage, etc...), the service never tries to subscribe back to the command topic.
You have to restart the service to make the commands work again.
It could be a great enhancement to check if subscription is still active.

**Comment by SebLz** [comment]
Hello @smillier, I've pushed a commit to address this (https://github.com/SebLz/ha-addons/commit/3fd9c45ecc6bdf7c5f01b07cb78882ee7c2c158e), is this better on the new version ?

**Comment by smillier** [comment]
It seems to be working fine now. Thanks for the improvement.
