### ISSUE TITLE
Translation of the cloud script

### ISSUE THREAD

**Issue by leutnantlurch** [SebLz/ha-addons#55]
Hello there :) 

Is there a way to translate the cloudscript?

https://github.com/SebLz/ha-addons/blob/main/maestro_gateway/rootfs/maestro/cloud/_data_.py

I would do it myself but unfortunately, i don't know how :( 

Thanks in advance :)

**Comment by SebLz** [comment]
Hello @leutnantlurch, I've added some translations in the lastest version, feel free to try them out.

**Comment by sinjorgo** [comment]
> Hello @leutnantlurch, I've added some translations in the lastest version, feel free to try them out.

Hello SebLz, I have tried the translation but only "fr" seems to work. When I try any other like nl, it or de I can't see any information anymore in the integration. 
Do I have to enter something else instead of nl, like Netherlands or so?

**Comment by SebLz** [comment]
"nl" works just fine here:
![image](https://github.com/SebLz/ha-addons/assets/190146/a45543f3-9523-4918-b9d0-5ce4977139a8)

I haven't developped any integration, just this addon, are you possibly mixing someone else's integration with this addon ?

**Comment by sinjorgo** [comment]
Hi SebLz,
I ment addon and not integration. Thanks for the screenshot, I have found what I did wrong and it is working fine now.
